language: python
services: postgresql
python:
- '2.7'
addons:
- postgresql: '9.1'
before_install:
- openssl aes-256-cbc -K $encrypted_b7bd3aa10e46_key -iv $encrypted_b7bd3aa10e46_iv
  -in .private/private_data.tar.enc -out private_data.tar -d
install:
- pip install kamaki==0.13.1
- pip install paramiko
- pip install ansible==1.9.2
- pip install django
- pip install djorm-pgarray
- pip install psycopg2
- pip install djangorestframework
- pip install rest_framework_ember
- pip install selenium
- pip install nose-cov
- pip install requests
- pip install django-celery
- pip install django-admin-bootstrapped
- sudo apt-get install shunit2
before_script:
- psql -c 'create user developer with createdb;' -U postgres
- psql -c 'create database portal with owner developer;' -U postgres
- tar -xvf private_data.tar
- python webapp/manage.py syncdb --noinput
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16
- python webapp/manage.py runserver 0.0.0.0:8000 --noreload &
- sleep 10s
script:
- nosetests tests/web/test_portal.py
after_script:
- sudo killall -s INT python